version: "3.9"

services:
  web:
    build: .
    container_name: myneuron-backend1
    ports:
      - "9006:8000"
    volumes:
      - .:/app
    
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: myneuron_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'myneuron'
      MYSQL_USER: 'Tufan'
      MYSQL_PASSWORD: 'Tufan@253385'
      MYSQL_ROOT_PASSWORD: 'Tufan@253385'
    volumes:
      - /bencos/myneuron/db:/var/lib/mysql
    ports:
      - "3305:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myneuron_phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_USER: 'Tufan'
      PMA_PASSWORD: 'Tufan@253385'